ALTER TABLE Employe
ADD COLUMN ID_Ligue INT,
ADD COLUMN ID_Role INT;


ALTER TABLE Employe
ADD CONSTRAINT FK_ID_Ligue 
FOREIGN KEY (ID_Ligue) REFERENCES Ligue(ID_Ligue);

ALTER TABLE Employe
ADD CONSTRAINT FK_ID_Role 
FOREIGN KEY (ID_Role) REFERENCES Role(ID_Role);